# Generated by Django 4.2.26 on 2025-11-13 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='板块名称')),
                ('description', models.TextField(blank=True, verbose_name='板块描述')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='板块图标')),
                ('order', models.IntegerField(choices=[(1, '第1位'), (2, '第2位'), (3, '第3位'), (4, '第4位'), (5, '第5位')], default=1, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('moderator_only', models.BooleanField(default=False, verbose_name='仅管理员可见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '论坛板块',
                'verbose_name_plural': '论坛板块',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('status', models.CharField(choices=[('published', '已发布'), ('draft', '草稿'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='状态')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_essence', models.BooleanField(default=False, verbose_name='是否精华')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='回复次数')),
                ('last_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='最后回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.forum', verbose_name='所属板块')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-is_top', '-last_reply_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='主题名称')),
                ('identifier', models.CharField(max_length=20, unique=True, verbose_name='主题标识符')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('signature', models.CharField(blank=True, max_length=100, verbose_name='个性签名')),
                ('post_count', models.IntegerField(default=0, verbose_name='发帖数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='回复数')),
                ('reputation', models.IntegerField(default=0, verbose_name='声望值')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='myapp.reply', verbose_name='父回复')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.post', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reply', '回复'), ('mention', '提及'), ('system', '系统通知')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='变量名')),
                ('value', models.CharField(max_length=100, verbose_name='变量值')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='myapp.theme', verbose_name='所属主题')),
            ],
            options={
                'verbose_name': '主题变量',
                'verbose_name_plural': '主题变量',
                'ordering': ['name'],
                'unique_together': {('theme', 'name')},
            },
        ),
    ]
